spring:
  application.name: reservation
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reservation}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
